### ISSUE TITLE
Add support to automatic/on prompt collapsing/expanding multiple layers of a JSON

### ISSUE THREAD

**Issue by TheYuriG** [jribbens/json-wrangler#2]
As it is, you need to manually collapse every item of the read object. This can become a chore really quickly if you have a large object with several properties or indexes in arrays.

This issue aims to have options/buttons to remedy this problem.

The button version of this implementation could have two options: one for collapsing/extending the next layer and one toggle button to collapse/extend all layers.

The options menu of this implementation would offer a checkbox to auto-collapse all layers upon loading and a dropdown menu to select which layer you would like to collapse all content to. The reason for layered collapsing is because usually the first 1 or 2 layers of a JSON will always be the same (data/message/response) and not worth collapsing further down.

**Comment by jribbens** [comment]
From the README:

* Ctrl-clicking (Command-clicking on MacOS) on the '-' or '+' will, rather than toggling the item you're clicking on, instead open or close every item immediately contained within this one, which makes it very easy to see a list of the properties of an object, or the members of an array.

Does that do what you want?

**Comment by TheYuriG** [comment]
> Does that do what you want?

Nope.

> The button version of this implementation could have two options: one for collapsing/extending the next layer and one toggle button to collapse/extend all layers.

The idea was to have [+] and [-] buttons to expand or collapse a whole level of indentation and the other to collapse/extend the entire JSON to the minimum/maximum.

Either way, I'm gonna close this issue as I just ended up using a GUI tool like Postman, no longer use the extension and see no reason to get you to work on a feature I have no intention of using anymore.
